# akms
# Key : Value
# kubernetes Object (Pod, RelicaSet, Deployment, Services, Ingress)
# Pod - v1
apiVersion: v1
kind: Pod
metadata:
 name: mypod
spec:
 containers:
  - name: mycontainer
    image: nginx
    ports:
    - containerPort: 80

